[build-system]
requires = ["setuptools",
            "wheel",
            "Cython",
            "oldest-supported-numpy; python_version >= '3.8'",
            "numpy==1.16.1; python_version <= '3.7' and python_version >= '3'",
            "numpy==1.13.3; python_version=='2.7'",
            "scipy"]